### PR TITLE
Updating ER diagram

### PR DESCRIPTION
**Pull request by ignasposka**

### CODE REVIEW

**Comment by psaulenas** [comment]
Maybe would be possible to also add a file that would be editable?

**Comment by ignasposka** [comment]
> Maybe would be possible to also add a file that would be editable?

I will try to get it from LucidChart

**Comment by ignasposka** [comment]
@psaulenas I cannot export editable file, because it's a premium feature...

**Comment by AzisK** [comment]
I suppose we can make the country an ENUM since there is a known number of countries in the world. Either ISO-2 or ISO-3 code or even the full country name. What do you think?

**Review by AzisK — CHANGES_REQUESTED** [review]
- app_user mod_time is missing NOT NULL
- organization id was changed from SMALLSERIAL to SERIAL based on https://github.com/pets-oss/pets-back/pull/17#discussion_r537478494
- registration_date is missing in animal according to https://github.com/pets-oss/pets-back/pull/17#issuecomment-740102577

**Comment by ignasposka** [comment]
> I suppose we can make the country an ENUM since there is a known number of countries in the world. Either ISO-2 or ISO-3 code or even the full country name. What do you think?

Yes, we can do it. I will update diagram.

**Review by AzisK — APPROVED** [review]
Good job! We also have NOT NULL next to registration_date but I am not sure how that should look like in ERD

**Pull request merged**
